import Footer from 'components/Footer';
import Header from 'components/Header';
import ProjectList from 'components/ProjectList';
import Head from 'next/head';

export default function Projects() {
	return (
		<>
			<Head>
				<title>twinedo.dev</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<ProjectList />
			<Footer />
		</>
	);
}
