import Head from 'next/head';
import Header from 'components/Header';
import Hero from 'components/Hero';
import Socmed from 'components/Socmed';
import HomeProjects from 'components/HomeProjects';
import Experiences from 'components/Experiences';

export default function Home() {
	return (
		<>
			<Head>
				<title>twinedo.dev</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Hero />
			<Socmed />
			<HomeProjects />
			<Experiences />
		</>
	);
}
